openapi: "3.0.3"
info:
  title: "com_hasancbngl_hero_server API"
  description: "com_hasancbngl_hero_server API"
  version: "1.0.0"
servers:
- url: "https://com_hasancbngl_hero_server"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Welcome to Hero API!"
  /heroes:
    get:
      description: ""
      parameters:
      - name: "page"
        in: "query"
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /heroes/search:
    get:
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponse"
components:
  schemas:
    Hero:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        image:
          type: "string"
        about:
          type: "string"
        rating:
          type: "number"
          format: "double"
        power:
          type: "integer"
          format: "int32"
        month:
          type: "string"
        day:
          type: "string"
        family:
          type: "array"
          items:
            type: "string"
        abilities:
          type: "array"
          items:
            type: "string"
        natureTypes:
          type: "array"
          items:
            type: "string"
    ApiResponse:
      type: "object"
      properties:
        success:
          type: "boolean"
        message:
          type: "string"
        prevPage:
          type: "integer"
          format: "int32"
        nextPage:
          type: "integer"
          format: "int32"
        heroes:
          type: "array"
          items:
            $ref: "#/components/schemas/Hero"